# Generated by Django 2.2.1 on 2019-05-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='is_ativo',
            field=models.BooleanField(default=True),
        ),
    ]
